# Generated by Django 5.1.2 on 2024-10-18 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название базы данных"
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("phonetic", "Фонетическая"),
                            ("textual", "Текстовая"),
                            ("image", "С изображениями"),
                        ],
                        max_length=50,
                        verbose_name="Тип базы данных",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataObject",
            fields=[
                (
                    "sequence_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название/Описание объекта"
                    ),
                ),
                ("language", models.CharField(max_length=100, verbose_name="Язык")),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                ("file", models.FileField(upload_to="files/")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Регион"
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_objects",
                        to="database.database",
                        verbose_name="База данных",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/", verbose_name="Файл")),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_file", models.FileField(upload_to="processing_results/")),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("vowels", "Гласные"),
                            ("consonants", "Согласные"),
                            ("prosody", "Просодия"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.dataobject",
                    ),
                ),
            ],
        ),
    ]
